# Generated by Django 3.2.14 on 2023-01-18 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_account_is_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Appname', models.CharField(max_length=500, null=True)),
                ('Applink', models.CharField(max_length=500, null=True)),
                ('appcategory', models.CharField(max_length=500, null=True)),
                ('subcategory', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='my_points',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
