# Generated by Django 3.2.14 on 2023-01-18 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20230118_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='completedTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='name_app', to='accounts.app')),
            ],
        ),
    ]
