# Generated by Django 3.2.14 on 2023-01-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_app_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedtask',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
